name: unit-test

on:
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependecies
        run: yarn install
      - name: Build
        run: yarn build
  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependecies
        run: yarn install
      - name: Run unit tests and display coverage
        run: yarn test-coverage
      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-artifact
          path: coverage/cobertura-coverage.xml
          retention-days: 1
  generate-coverage-comment:
    runs-on: ubuntu-latest
    needs: [run-unit-tests]
    continue-on-error: true
    permissions:
      discussions: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-artifact
          path: ./coverage
      - name: Generate coverage comment
        uses: ewjoachim/coverage-comment-action@v1.0.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_FILE: "coverage/cobertura-coverage.xml"

        
