name: unit-test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependecies
        run: yarn install
      - name: Cat the package.json file
        run: cat package.json
      - name: Run unit tests and collect coverage
        run: yarn test-coverage
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/clover.xml
          badge: true

        
