name: unit-test

on:
  pull_request:
    branches:
      - 'master'

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.Js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm i -g yarn
      - name: Install dependecies
        run: yarn install
      - name: Run unit tests and display coverage
        run: yarn test-coverage

        
